AWSTemplateFormatVersion: "2010-09-09"

Description: "Organize for ID Pool"

Transform: 
  - "AWS::LanguageExtensions"

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Metadata                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: User Pool Configuration
        Parameters:
          - AuthUserEmail

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Parameters                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Parameters:
  AuthUserEmail:
    Description: Auth User Email Address
    Type: String
  
# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Mappings                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Mappings: 
  IamParams:
    PolicyCommon:
      Description: Get Credentials from ID pool
      Name: iam-policy-get-credentials
    RoleAnonymous:
      Description: Cognito ID pool Anonymous User
      Name: iam-role-anonymous-user
    RoleAuthenticated:
      Description: Cognito ID pool Authenticated User
      Name: iam-role-authenticated-user

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Conditions                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Conditions: 

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Resources                                                                                     ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Resources:
  # -------------------------------------
  # Cognito User pool
  # -------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: "user-pool-for-id-pool"
      ### Authentication
      # Sign-in Attributes
      AliasAttributes:
        - email
      # Sign-up Attributes
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: birthdate
          AttributeDataType: String
          Required: true
          Mutable: true
          DeveloperOnlyAttribute: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      ### Settings
      UserPoolTier: "ESSENTIALS"
      UserPoolTags:
        Name: "user-pool-for-id-pool"
      DeletionProtection: INACTIVE

  # -------------------------------------
  # APP Client - spa
  # -------------------------------------
  SpaClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "spa-app"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      AuthSessionValidity: 3
      RefreshTokenValidity: 5
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      EnableTokenRevocation: true
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH

  # -------------------------------------
  # Cognito ID pool
  # -------------------------------------
  IdPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: "id-pool"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ProviderName: !GetAtt UserPool.ProviderName
          ClientId: !Ref SpaClient
      IdentityPoolTags:
        - Key: Name
          Value: "id-pool"

  # -------------------------------------
  # IAM Policy - Common
  # -------------------------------------
  PolicyCommon:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !FindInMap [IamParams, PolicyCommon, Description]
      ManagedPolicyName: !FindInMap [IamParams, PolicyCommon, Name]
      PolicyDocument:
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AllowGetCredentialsFromIdPool",
                    "Effect": "Allow",
                    "Action": [
                        "cognito-identity:GetCredentialsForIdentity"
                    ],
                    "Resource": [
                        "*"
                    ]
                }
            ]
        }

  # -------------------------------------
  # IAM Role - Anonymous User
  # -------------------------------------
  RoleForAnonymous:
    Type: AWS::IAM::Role
    Properties:
      Description: !FindInMap [IamParams, RoleAnonymous, Description]
      RoleName: !FindInMap [IamParams, RoleAnonymous, Name]
      AssumeRolePolicyDocument:
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "cognito-identity.amazonaws.com"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "cognito-identity.amazonaws.com:aud": { Ref: IdPool }
                        },
                        "ForAnyValue:StringLike": {
                            "cognito-identity.amazonaws.com:amr": "unauthenticated"
                        }
                    }
                }
            ]
        }
      ManagedPolicyArns:
        - !Ref PolicyCommon
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: Name
          Value: !FindInMap [IamParams, RoleAnonymous, Name]

  # -------------------------------------
  # IAM Role - Authenticated User
  # -------------------------------------
  RoleForAuthenticated:
    Type: AWS::IAM::Role
    Properties:
      Description: !FindInMap [IamParams, RoleAuthenticated, Description]
      RoleName: !FindInMap [IamParams, RoleAuthenticated, Name]
      AssumeRolePolicyDocument:
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "cognito-identity.amazonaws.com"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "cognito-identity.amazonaws.com:aud": { Ref: IdPool }
                        },
                        "ForAnyValue:StringLike": {
                            "cognito-identity.amazonaws.com:amr": "authenticated"
                        }
                    }
                }
            ]
        }
      ManagedPolicyArns:
        - !Ref PolicyCommon
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: Name
          Value: !FindInMap [IamParams, RoleAuthenticated, Name]

  # -------------------------------------
  # Role Attachment to ID pool
  # -------------------------------------
  AttachRoleIdPool:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdPool
      Roles: 
        "authenticated": !GetAtt RoleForAuthenticated.Arn
        "unauthenticated": !GetAtt RoleForAnonymous.Arn

  # -------------------------------------
  # Add User to User Pool Directory
  # -------------------------------------
  AuthUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPool
      Username: testuser
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref AuthUserEmail
        - Name: email_verified
          Value: "true"
        - Name: birthdate
          Value: "2000-11-11"

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Outputs                                                                                       ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Outputs: